### PR TITLE
Hel fix1

### PR DESCRIPTION
**Pull request by kyrsjo**
Some small changes. I rebased on top of the commits you did this afternoon/morning, in case you're wondering why all my commits appear as if they happened after yours.

Could you please check and fast forward?

### CODE REVIEW

**Comment by mfittere** [comment]
Thanks for all the changes!

In general the changes are fine with me. Could you please still
1)  check that everything works with the readin for your version of the Daten input block, explicitly:
- does it fail if you forget to define the elens in the ELEN block
- do the checks for the el(i)=0 work
- does the check for the kz(i)=29 work
2) what is the difference between the round_near and fround?

**Comment by mfittere** [comment]
Thanks for all the changes!

In general the changes are fine with me. Could you please still
1. check that everything works with the readin for your version of the Daten input block, explicitly:
- does it fail if you forget to define the elens single element in the ELEN block?
- do the checks for the el(i)=0 work?
- does the check for the kz(i)=29 work?
1. what is the difference between the round_near and fround?

**Comment by kyrsjo** [comment]
Tests, part1:
- Commenting out an element from the ELEN block, so that one of the SINGLE ELEMENTS are not fully initalized, results in the error message:
  `ERROR: elens hel3 with kz(         110 ) =           29  is not defined in fort.3. You must define every elens in the ELEN block in fort.3!` -> OK 👍 
- Adding a non-existing ELENS such as "hel42 ANNULAR 4.920e-03 6.928 1.5 0 2.3093 0 0" results in the error message `ERROR in ELEN: Un-identified SINGLE ELEMENT 'hel42'`-> OK 👍 
- Changing `el` to 1.0 in `hel1` :  `ERROR: length el(j) (elens is treated as thin element),  and first and second field have to be zero: el(j)=ed(j)=ek(j)=0, while el(         108 )=   0.0000000000000000      , ed(         108 )=   1.0000000000000000      , ek(         108 )=   0.0000000000000000      . Note that el(j) is set to 0 inside the code and then length is stored in elens_length(ix).` -> OK 👍

**Comment by kyrsjo** [comment]
(now pulling the new mfittere/hel after https://github.com/SixTrack/SixTrack/pull/81/commits/35d25ea71a173bfab6d6cf847eb5cf2131eec37f  and continuing checks...)

**Comment by kyrsjo** [comment]
Continuing tests:
- Changing `ed` to 1.0 again: `ERROR: length el(j) (elens is treated as thin element),  and first and second field have to be zero: el(j)=ed(j)=ek(j)=0, while el(         108 )=   0.0000000000000000      , ed(         108 )=   1.0000000000000000      , ek(         108 )=   0.0000000000000000      .` 👍 
- Changing `ek` to 1.0: `ERROR: length el(j) (elens is treated as thin element),  and first and second field have to be zero: el(j)=ed(j)=ek(j)=0, while el(         108 )=   0.0000000000000000      , ed(         108 )=   0.0000000000000000      , ek(         108 )=   1.0000000000000000      .` 👍 
- Changing `el` to 1.0: `ERROR: length el(j) (elens is treated as thin element),  and first and second field have to be zero: el(j)=ed(j)=ek(j)=0, while el(         108 )=   1.0000000000000000      , ed(         108 )=   0.0000000000000000      , ek(         108 )=   0.0000000000000000      .` 👍 

OK! One thing, the error message is maybe a bit strange now?

**Comment by kyrsjo** [comment]
MISTAKE (mine):

This elens block is not valid:

```
ELEN
hel1 ANNULAR 4.920e-03 6.928 1.5 0 0 0 0
hel2 ANNULAR 4.920e-03 6.928 1.5 1.1547 2.3093 0 0
hel3 ANNULAR 4.920e-03 6.928 1.5 1.1547 0 0 0
hel4 ANNULAR 4.920e-03 6.928 1.5 0 2.3093 0 0
hel3 ANNULAR 4.920e-03 6.928 1.5 1.1547 0 0 0
NEXT
```

This is detected:

```
 ERROR in ELEN block:The element 'hel3            ' was defined twice!
ELENS found in list of single elements with: 
name     = hel3            
type     = ANNULAR =    1
thetamax = 0.492D-02 mrad
r2       = 0.693D+01 mm
r2/r1    = 0.150D+01
offset_x = 0.115D+01 mm
offset_y = 0.000D+00 mm
enable bends at:
  entrance =    0
  exit     =    0
```

By the code:

```
            if (elens_type(j).ne.0) then
+if cr
               write(lout,*) "ERROR in ELEN block:"//
+ei
+if .not.cr
               write(*,*)    "ERROR in ELEN block:"//
+ei
     &              "The element '"//bez(j)//"' was defined twice!"
            endif
```

However the `call prror(-1)` is missing... Could you please add it and push?

**Comment by kyrsjo** [comment]
Checking special tests for "ANNULAR":
- r2/r1 > 0: `hel4 ANNULAR 4.920e-03 6.928 1.0 0 2.3093 0 0` -> `ERROR: ELEN radius ratio r2/r1 must be larger than 1, but is    1.0000000000000000      <1`  👍  (also checked -10)
- `elens_bend_exit` not in {-1,0,1}: Checked all the valid -> OK, it ran 👍  (did not check tracking results); checked value=2 -> `ERROR: ELEN flag for taking bends at exit into account must be -1,0,1, but elens_bend_exit =           2` -> OK 👍 
- Same for `elens_bend_entrance`: Ran for -1,0,1, crash for -4: `ERROR: ELEN flag for taking bends at entrance into account must be -1,0,1, but elens_bend_entrance =          -4` 👍 
- Type = `CIRCULAR`:  `ERROR in ELEN:Elens type 'CIRCULAR' not recognized. Remember to use all UPPER CASE!` -> Almost OK, but there should be a space between "ELEN:" and "Elens type...". Could you please fix? 🎱 
- Number of arguments == 9: `ERROR in ELEN block: wrong number of input parameters: ninput =            8  != 9` -> OK 👍

**Comment by mfittere** [comment]
fixed

**Pull request merged**
