### PR TITLE
Define the crlibm functions where they are used

### PR DESCRIPTION
**Pull request by kyrsjo**
Hi Miriam,

Seems you never defined the _rn functions; In FORTRAN you must define a functions to use it. I used ASTUCE to add some definitions.

Try now?

### CODE REVIEW

**Comment by kyrsjo** [comment]
I'll add some example where I remove implicit variables, please wait with accepting...

**Comment by mfittere** [comment]
can I merge? I would be ready.

Do you really think it is necessary to go through all the trouble of defining the variable explicitly as long as it works also with the implicit definition?

**Comment by kyrsjo** [comment]
OK, done; I made an example out of the TUNENEWT function also.

At _least_ make everything explicit in all functions you modify; it's not difficult and it doesn't take a lot of time. This would have avoided the problem in the first place; commenting out the "+ca crlibco" from the fixed version of TUNENEWT1 results in the following errors:

```
gfortran -c -frecord-marker=4 -O4 -m32 -g -fno-second-underscore -funroll-loops -mfpmath=sse -msse2 plato_seq.f -o plato_seq.o
plato_seq.f:96:19:

       DUEPI=ATAN_RN(1D0)*8D0
                   1
Error: Function ‘atan_rn’ at (1) has no IMPLICIT type
plato_seq.f:97:42:

       write(*,*) 'atan,atan_rn',ATAN(1D0),ATAN_RN(1D0)
                                          1
Error: Function ‘atan_rn’ at (1) has no IMPLICIT type
plato_seq.f:102:15:

      &log(2d0),LOG_RN(2.0D0)
               1
Error: Function ‘log_rn’ at (1) has no IMPLICIT type
plato_seq.f:103:29:

       write(*,*) 'logrnmaxn',
                             1
Error: Function ‘log_rn’ at (1) has no IMPLICIT type
plato_seq.f:106:32:

      &LOG_RN(FLOAT(MAXN))/LOG_RN(2D0)
                                1
Error: Function ‘log_rn’ at (1) has no IMPLICIT type
plato_seq.f:108:36:

      &INT(LOG_RN(FLOAT(MAXN))/LOG_RN(2D0))
                                    1
Error: Function ‘log_rn’ at (1) has no IMPLICIT type
plato_seq.f:109:40:

       MFT=INT(LOG_RN(FLOAT(MAXN))/LOG_RN(2D0))
                                        1
Error: Function ‘log_rn’ at (1) has no IMPLICIT type
plato_seq.f:361:21:

       CALL FFT_PLATO(ZSING,NPOINT,-1)
                     1
```

This would surely alerted you to the problem.

Description of how the IMPLICIT statement works:
https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn9v/index.html
Rules for data typing (if no IMPLICIT NONE):
https://docs.oracle.com/cd/E19957-01/805-4939/z40007365fbc/index.html
Note that the "standard" is real (except for those variables starting with I, J, K, L, M, or N) - that is single precision reals aka REAL*4. So this is what the LOG_RN etc. was declared as, instead of the DOUBLE PRECISION it should have been. And since FORTRAN doesn't really check anything related to calling functions, a train wreck ensues.

Therefore: _Implicit - not even once_.

**Comment by kyrsjo** [comment]
You may pull.

**Pull request merged**
